### ISSUE TITLE
Unable to add global "environmentLabel" as the runtime or the extensions have already been initialized.

### ISSUE THREAD

**Issue by justinmacleod** [TopShelfCraft/Environment-Label#6]
We are experiencing an issue when we attempt to activate Environment Label. I believe the issue is similar to TopShelfCraft/Wordsmith#6. I'm running the latest version of Craft (3.0.29) with PHP version 7.2.9. 

```
LogicException: Unable to add global "environmentLabel" as the runtime or the extensions have already been initialized. in /home/vagrant/craft-starter/vendor/twig/twig/lib/Twig/Environment.php:882
Stack trace:
#0 /home/vagrant/craft-starter/vendor/topshelfcraft/environment-label/src/EnvironmentLabel.php(61): Twig_Environment->addGlobal('environmentLabe...', Object(topshelfcraft\environmentlabel\services\Label))
#1 /home/vagrant/craft-starter/vendor/yiisoft/yii2/base/BaseObject.php(109): topshelfcraft\environmentlabel\EnvironmentLabel->init()
#2 /home/vagrant/craft-starter/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#3 /home/vagrant/craft-starter/vendor/craftcms/cms/src/base/Plugin.php(113): yii\base\Module->__construct('environment-lab...', Object(craft\web\Application), Array)
#4 [internal function]: craft\base\Plugin->__construct('environment-lab...', Object(craft\web\Application), Array)
#5 /home/vagrant/craft-starter/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#6 /home/vagrant/craft-starter/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('topshelfcraft\\e...', Array, Array)
#7 /home/vagrant/craft-starter/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('topshelfcraft\\e...', Array, Array)
#8 /home/vagrant/craft-starter/vendor/craftcms/cms/src/services/Plugins.php(788): yii\BaseYii::createObject(Array, Array)
#9 /home/vagrant/craft-starter/vendor/craftcms/cms/src/services/Plugins.php(448): craft\services\Plugins->createPlugin('environment-lab...')
#10 /home/vagrant/craft-starter/vendor/craftcms/cms/src/controllers/PluginsController.php(48): craft\services\Plugins->installPlugin('environment-lab...')
#11 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#12 /home/vagrant/craft-starter/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /home/vagrant/craft-starter/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /home/vagrant/craft-starter/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('install-plugin', Array)
#15 /home/vagrant/craft-starter/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#16 /home/vagrant/craft-starter/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('plugins/install...', Array)
#17 /home/vagrant/craft-starter/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('plugins/install...', Array)
#18 /home/vagrant/craft-starter/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /home/vagrant/craft-starter/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /home/vagrant/craft-starter/web/index.php(21): yii\base\Application->run()
#21 {main}
```

**Comment by jalendport** [comment]
Thanks for letting us know @justinmacleod, we'll look into it right away!
